<script lang="ts">
  const dodSize = 3;

  const textColor = () => {
    if (Math.random() < 0.4) {
      return 'fill-fv-tx-primary';
    } else {
      return 'fill-fv-tx-tertiary';
    }
  };
  const backGroundColor = () => {
    if (Math.random() < 0.1) {
      return 'fill-fv-bg-primary';
    } else {
      return 'fill-fv-bg-tertiary';
    }
  };
</script>

<svg
  class="h-auto w-full"
  viewBox="0 0 578 218"
  fill="none"
  xmlns="http://www.w3.org/2000/svg"
>
  <circle cx="34" cy="64" r={dodSize} class={textColor()} />
  <circle cx="34" cy="74" r={dodSize} class={textColor()} />
  <circle cx="34" cy="84" r={dodSize} class={textColor()} />
  <circle cx="34" cy="94" r={dodSize} class={textColor()} />
  <circle cx="34" cy="104" r={dodSize} class={textColor()} />
  <circle cx="34" cy="114" r={dodSize} class={textColor()} />
  <circle cx="34" cy="124" r={dodSize} class={textColor()} />
  <circle cx="34" cy="134" r={dodSize} class={textColor()} />
  <circle cx="44" cy="64" r={dodSize} class={textColor()} />
  <circle cx="44" cy="74" r={dodSize} class={textColor()} />
  <circle cx="44" cy="84" r={dodSize} class={textColor()} />
  <circle cx="44" cy="94" r={dodSize} class={textColor()} />
  <circle cx="44" cy="104" r={dodSize} class={textColor()} />
  <circle cx="44" cy="114" r={dodSize} class={textColor()} />
  <circle cx="44" cy="124" r={dodSize} class={textColor()} />
  <circle cx="44" cy="134" r={dodSize} class={textColor()} />
  <circle cx="54" cy="74" r={dodSize} class={textColor()} />
  <circle cx="54" cy="84" r={dodSize} class={textColor()} />
  <circle cx="64" cy="74" r={dodSize} class={textColor()} />
  <circle cx="64" cy="84" r={dodSize} class={textColor()} />
  <circle cx="64" cy="94" r={dodSize} class={textColor()} />
  <circle cx="64" cy="104" r={dodSize} class={textColor()} />
  <circle cx="64" cy="114" r={dodSize} class={textColor()} />
  <circle cx="64" cy="124" r={dodSize} class={textColor()} />
  <circle cx="64" cy="134" r={dodSize} class={textColor()} />
  <circle cx="74" cy="74" r={dodSize} class={textColor()} />
  <circle cx="74" cy="84" r={dodSize} class={textColor()} />
  <circle cx="74" cy="94" r={dodSize} class={textColor()} />
  <circle cx="74" cy="104" r={dodSize} class={textColor()} />
  <circle cx="74" cy="114" r={dodSize} class={textColor()} />
  <circle cx="74" cy="124" r={dodSize} class={textColor()} />
  <circle cx="74" cy="134" r={dodSize} class={textColor()} />
  <circle cx="84" cy="74" r={dodSize} class={textColor()} />
  <circle cx="84" cy="84" r={dodSize} class={textColor()} />
  <circle cx="94" cy="74" r={dodSize} class={textColor()} />
  <circle cx="94" cy="84" r={dodSize} class={textColor()} />
  <circle cx="94" cy="94" r={dodSize} class={textColor()} />
  <circle cx="94" cy="104" r={dodSize} class={textColor()} />
  <circle cx="94" cy="114" r={dodSize} class={textColor()} />
  <circle cx="94" cy="124" r={dodSize} class={textColor()} />
  <circle cx="94" cy="134" r={dodSize} class={textColor()} />
  <circle cx="104" cy="74" r={dodSize} class={textColor()} />
  <circle cx="104" cy="84" r={dodSize} class={textColor()} />
  <circle cx="104" cy="94" r={dodSize} class={textColor()} />
  <circle cx="104" cy="104" r={dodSize} class={textColor()} />
  <circle cx="104" cy="114" r={dodSize} class={textColor()} />
  <circle cx="104" cy="124" r={dodSize} class={textColor()} />
  <circle cx="104" cy="134" r={dodSize} class={textColor()} />
  <circle cx="324" cy="74" r={dodSize} class={textColor()} />
  <circle cx="324" cy="84" r={dodSize} class={textColor()} />
  <circle cx="324" cy="124" r={dodSize} class={textColor()} />
  <circle cx="324" cy="134" r={dodSize} class={textColor()} />
  <circle cx="444" cy="94" r={dodSize} class={textColor()} />
  <circle cx="444" cy="104" r={dodSize} class={textColor()} />
  <circle cx="444" cy="114" r={dodSize} class={textColor()} />
  <circle cx="124" cy="54" r={dodSize} class={textColor()} />
  <circle cx="124" cy="74" r={dodSize} class={textColor()} />
  <circle cx="124" cy="84" r={dodSize} class={textColor()} />
  <circle cx="124" cy="94" r={dodSize} class={textColor()} />
  <circle cx="124" cy="104" r={dodSize} class={textColor()} />
  <circle cx="124" cy="114" r={dodSize} class={textColor()} />
  <circle cx="124" cy="124" r={dodSize} class={textColor()} />
  <circle cx="124" cy="134" r={dodSize} class={textColor()} />
  <circle cx="224" cy="74" r={dodSize} class={textColor()} />
  <circle cx="224" cy="84" r={dodSize} class={textColor()} />
  <circle cx="224" cy="94" r={dodSize} class={textColor()} />
  <circle cx="224" cy="104" r={dodSize} class={textColor()} />
  <circle cx="224" cy="114" r={dodSize} class={textColor()} />
  <circle cx="224" cy="124" r={dodSize} class={textColor()} />
  <circle cx="224" cy="134" r={dodSize} class={textColor()} />
  <circle cx="334" cy="74" r={dodSize} class={textColor()} />
  <circle cx="334" cy="84" r={dodSize} class={textColor()} />
  <circle cx="454" cy="84" r={dodSize} class={textColor()} />
  <circle cx="454" cy="94" r={dodSize} class={textColor()} />
  <circle cx="454" cy="104" r={dodSize} class={textColor()} />
  <circle cx="454" cy="114" r={dodSize} class={textColor()} />
  <circle cx="454" cy="124" r={dodSize} class={textColor()} />
  <circle cx="134" cy="54" r={dodSize} class={textColor()} />
  <circle cx="134" cy="74" r={dodSize} class={textColor()} />
  <circle cx="134" cy="84" r={dodSize} class={textColor()} />
  <circle cx="134" cy="94" r={dodSize} class={textColor()} />
  <circle cx="134" cy="104" r={dodSize} class={textColor()} />
  <circle cx="134" cy="114" r={dodSize} class={textColor()} />
  <circle cx="134" cy="124" r={dodSize} class={textColor()} />
  <circle cx="134" cy="134" r={dodSize} class={textColor()} />
  <circle cx="234" cy="74" r={dodSize} class={textColor()} />
  <circle cx="234" cy="84" r={dodSize} class={textColor()} />
  <circle cx="234" cy="94" r={dodSize} class={textColor()} />
  <circle cx="234" cy="104" r={dodSize} class={textColor()} />
  <circle cx="234" cy="114" r={dodSize} class={textColor()} />
  <circle cx="234" cy="124" r={dodSize} class={textColor()} />
  <circle cx="234" cy="134" r={dodSize} class={textColor()} />
  <circle cx="464" cy="74" r={dodSize} class={textColor()} />
  <circle cx="464" cy="84" r={dodSize} class={textColor()} />
  <circle cx="464" cy="124" r={dodSize} class={textColor()} />
  <circle cx="464" cy="134" r={dodSize} class={textColor()} />
  <circle cx="244" cy="74" r={dodSize} class={textColor()} />
  <circle cx="244" cy="84" r={dodSize} class={textColor()} />
  <circle cx="244" cy="124" r={dodSize} class={textColor()} />
  <circle cx="244" cy="134" r={dodSize} class={textColor()} />
  <circle cx="354" cy="84" r={dodSize} class={textColor()} />
  <circle cx="354" cy="94" r={dodSize} class={textColor()} />
  <circle cx="354" cy="104" r={dodSize} class={textColor()} />
  <circle cx="354" cy="114" r={dodSize} class={textColor()} />
  <circle cx="354" cy="124" r={dodSize} class={textColor()} />
  <circle cx="354" cy="134" r={dodSize} class={textColor()} />
  <circle cx="474" cy="74" r={dodSize} class={textColor()} />
  <circle cx="474" cy="84" r={dodSize} class={textColor()} />
  <circle cx="474" cy="124" r={dodSize} class={textColor()} />
  <circle cx="474" cy="134" r={dodSize} class={textColor()} />
  <circle cx="254" cy="74" r={dodSize} class={textColor()} />
  <circle cx="254" cy="84" r={dodSize} class={textColor()} />
  <circle cx="254" cy="124" r={dodSize} class={textColor()} />
  <circle cx="254" cy="134" r={dodSize} class={textColor()} />
  <circle cx="364" cy="74" r={dodSize} class={textColor()} />
  <circle cx="364" cy="84" r={dodSize} class={textColor()} />
  <circle cx="364" cy="94" r={dodSize} class={textColor()} />
  <circle cx="364" cy="104" r={dodSize} class={textColor()} />
  <circle cx="364" cy="114" r={dodSize} class={textColor()} />
  <circle cx="364" cy="124" r={dodSize} class={textColor()} />
  <circle cx="364" cy="134" r={dodSize} class={textColor()} />
  <circle cx="154" cy="64" r={dodSize} class={textColor()} />
  <circle cx="154" cy="74" r={dodSize} class={textColor()} />
  <circle cx="154" cy="84" r={dodSize} class={textColor()} />
  <circle cx="154" cy="94" r={dodSize} class={textColor()} />
  <circle cx="154" cy="104" r={dodSize} class={textColor()} />
  <circle cx="154" cy="114" r={dodSize} class={textColor()} />
  <circle cx="154" cy="124" r={dodSize} class={textColor()} />
  <circle cx="154" cy="134" r={dodSize} class={textColor()} />
  <circle cx="264" cy="74" r={dodSize} class={textColor()} />
  <circle cx="264" cy="84" r={dodSize} class={textColor()} />
  <circle cx="264" cy="94" r={dodSize} class={textColor()} />
  <circle cx="264" cy="104" r={dodSize} class={textColor()} />
  <circle cx="264" cy="114" r={dodSize} class={textColor()} />
  <circle cx="264" cy="124" r={dodSize} class={textColor()} />
  <circle cx="264" cy="134" r={dodSize} class={textColor()} />
  <circle cx="374" cy="74" r={dodSize} class={textColor()} />
  <circle cx="374" cy="84" r={dodSize} class={textColor()} />
  <circle cx="374" cy="124" r={dodSize} class={textColor()} />
  <circle cx="374" cy="134" r={dodSize} class={textColor()} />
  <circle cx="164" cy="64" r={dodSize} class={textColor()} />
  <circle cx="164" cy="74" r={dodSize} class={textColor()} />
  <circle cx="164" cy="84" r={dodSize} class={textColor()} />
  <circle cx="164" cy="94" r={dodSize} class={textColor()} />
  <circle cx="164" cy="104" r={dodSize} class={textColor()} />
  <circle cx="164" cy="114" r={dodSize} class={textColor()} />
  <circle cx="164" cy="124" r={dodSize} class={textColor()} />
  <circle cx="164" cy="134" r={dodSize} class={textColor()} />
  <circle cx="274" cy="74" r={dodSize} class={textColor()} />
  <circle cx="274" cy="84" r={dodSize} class={textColor()} />
  <circle cx="274" cy="94" r={dodSize} class={textColor()} />
  <circle cx="274" cy="104" r={dodSize} class={textColor()} />
  <circle cx="274" cy="114" r={dodSize} class={textColor()} />
  <circle cx="274" cy="124" r={dodSize} class={textColor()} />
  <circle cx="274" cy="134" r={dodSize} class={textColor()} />
  <circle cx="384" cy="74" r={dodSize} class={textColor()} />
  <circle cx="384" cy="84" r={dodSize} class={textColor()} />
  <circle cx="384" cy="124" r={dodSize} class={textColor()} />
  <circle cx="494" cy="74" r={dodSize} class={textColor()} />
  <circle cx="494" cy="84" r={dodSize} class={textColor()} />
  <circle cx="494" cy="94" r={dodSize} class={textColor()} />
  <circle cx="494" cy="104" r={dodSize} class={textColor()} />
  <circle cx="494" cy="114" r={dodSize} class={textColor()} />
  <circle cx="494" cy="124" r={dodSize} class={textColor()} />
  <circle cx="494" cy="134" r={dodSize} class={textColor()} />
  <circle cx="174" cy="74" r={dodSize} class={textColor()} />
  <circle cx="174" cy="84" r={dodSize} class={textColor()} />
  <circle cx="394" cy="74" r={dodSize} class={textColor()} />
  <circle cx="394" cy="84" r={dodSize} class={textColor()} />
  <circle cx="394" cy="94" r={dodSize} class={textColor()} />
  <circle cx="394" cy="104" r={dodSize} class={textColor()} />
  <circle cx="394" cy="114" r={dodSize} class={textColor()} />
  <circle cx="394" cy="124" r={dodSize} class={textColor()} />
  <circle cx="394" cy="134" r={dodSize} class={textColor()} />
  <circle cx="504" cy="74" r={dodSize} class={textColor()} />
  <circle cx="504" cy="84" r={dodSize} class={textColor()} />
  <circle cx="504" cy="94" r={dodSize} class={textColor()} />
  <circle cx="504" cy="104" r={dodSize} class={textColor()} />
  <circle cx="504" cy="114" r={dodSize} class={textColor()} />
  <circle cx="504" cy="124" r={dodSize} class={textColor()} />
  <circle cx="504" cy="134" r={dodSize} class={textColor()} />
  <circle cx="184" cy="74" r={dodSize} class={textColor()} />
  <circle cx="184" cy="84" r={dodSize} class={textColor()} />
  <circle cx="404" cy="74" r={dodSize} class={textColor()} />
  <circle cx="404" cy="84" r={dodSize} class={textColor()} />
  <circle cx="404" cy="94" r={dodSize} class={textColor()} />
  <circle cx="404" cy="104" r={dodSize} class={textColor()} />
  <circle cx="404" cy="114" r={dodSize} class={textColor()} />
  <circle cx="404" cy="124" r={dodSize} class={textColor()} />
  <circle cx="404" cy="134" r={dodSize} class={textColor()} />
  <circle cx="514" cy="74" r={dodSize} class={textColor()} />
  <circle cx="514" cy="84" r={dodSize} class={textColor()} />
  <circle cx="514" cy="104" r={dodSize} class={textColor()} />
  <circle cx="514" cy="124" r={dodSize} class={textColor()} />
  <circle cx="514" cy="134" r={dodSize} class={textColor()} />
  <circle cx="194" cy="74" r={dodSize} class={textColor()} />
  <circle cx="194" cy="84" r={dodSize} class={textColor()} />
  <circle cx="194" cy="94" r={dodSize} class={textColor()} />
  <circle cx="194" cy="104" r={dodSize} class={textColor()} />
  <circle cx="194" cy="114" r={dodSize} class={textColor()} />
  <circle cx="194" cy="124" r={dodSize} class={textColor()} />
  <circle cx="194" cy="134" r={dodSize} class={textColor()} />
  <circle cx="294" cy="74" r={dodSize} class={textColor()} />
  <circle cx="294" cy="84" r={dodSize} class={textColor()} />
  <circle cx="524" cy="74" r={dodSize} class={textColor()} />
  <circle cx="524" cy="84" r={dodSize} class={textColor()} />
  <circle cx="524" cy="104" r={dodSize} class={textColor()} />
  <circle cx="524" cy="124" r={dodSize} class={textColor()} />
  <circle cx="524" cy="134" r={dodSize} class={textColor()} />
  <circle cx="204" cy="74" r={dodSize} class={textColor()} />
  <circle cx="204" cy="84" r={dodSize} class={textColor()} />
  <circle cx="204" cy="94" r={dodSize} class={textColor()} />
  <circle cx="204" cy="104" r={dodSize} class={textColor()} />
  <circle cx="204" cy="114" r={dodSize} class={textColor()} />
  <circle cx="204" cy="124" r={dodSize} class={textColor()} />
  <circle cx="204" cy="134" r={dodSize} class={textColor()} />
  <circle cx="304" cy="64" r={dodSize} class={textColor()} />
  <circle cx="304" cy="74" r={dodSize} class={textColor()} />
  <circle cx="304" cy="84" r={dodSize} class={textColor()} />
  <circle cx="304" cy="94" r={dodSize} class={textColor()} />
  <circle cx="304" cy="104" r={dodSize} class={textColor()} />
  <circle cx="304" cy="114" r={dodSize} class={textColor()} />
  <circle cx="304" cy="124" r={dodSize} class={textColor()} />
  <circle cx="304" cy="134" r={dodSize} class={textColor()} />
  <circle cx="424" cy="54" r={dodSize} class={textColor()} />
  <circle cx="424" cy="64" r={dodSize} class={textColor()} />
  <circle cx="424" cy="74" r={dodSize} class={textColor()} />
  <circle cx="424" cy="84" r={dodSize} class={textColor()} />
  <circle cx="424" cy="94" r={dodSize} class={textColor()} />
  <circle cx="424" cy="104" r={dodSize} class={textColor()} />
  <circle cx="424" cy="114" r={dodSize} class={textColor()} />
  <circle cx="424" cy="124" r={dodSize} class={textColor()} />
  <circle cx="424" cy="134" r={dodSize} class={textColor()} />
  <circle cx="534" cy="74" r={dodSize} class={textColor()} />
  <circle cx="534" cy="84" r={dodSize} class={textColor()} />
  <circle cx="534" cy="94" r={dodSize} class={textColor()} />
  <circle cx="534" cy="104" r={dodSize} class={textColor()} />
  <circle cx="534" cy="124" r={dodSize} class={textColor()} />
  <circle cx="534" cy="134" r={dodSize} class={textColor()} />
  <circle cx="314" cy="64" r={dodSize} class={textColor()} />
  <circle cx="314" cy="74" r={dodSize} class={textColor()} />
  <circle cx="314" cy="84" r={dodSize} class={textColor()} />
  <circle cx="314" cy="94" r={dodSize} class={textColor()} />
  <circle cx="314" cy="104" r={dodSize} class={textColor()} />
  <circle cx="314" cy="114" r={dodSize} class={textColor()} />
  <circle cx="314" cy="124" r={dodSize} class={textColor()} />
  <circle cx="314" cy="134" r={dodSize} class={textColor()} />
  <circle cx="434" cy="54" r={dodSize} class={textColor()} />
  <circle cx="434" cy="64" r={dodSize} class={textColor()} />
  <circle cx="434" cy="74" r={dodSize} class={textColor()} />
  <circle cx="434" cy="84" r={dodSize} class={textColor()} />
  <circle cx="434" cy="94" r={dodSize} class={textColor()} />
  <circle cx="434" cy="104" r={dodSize} class={textColor()} />
  <circle cx="434" cy="114" r={dodSize} class={textColor()} />
  <circle cx="434" cy="124" r={dodSize} class={textColor()} />
  <circle cx="434" cy="134" r={dodSize} class={textColor()} />
  <circle cx="544" cy="74" r={dodSize} class={textColor()} />
  <circle cx="544" cy="84" r={dodSize} class={textColor()} />
  <circle cx="544" cy="94" r={dodSize} class={textColor()} />
  <circle cx="544" cy="104" r={dodSize} class={textColor()} />
  <circle cx="544" cy="124" r={dodSize} class={textColor()} />
  <circle cx="544" cy="134" r={dodSize} class={textColor()} />
  <circle cx="124" cy="44" r={dodSize} class={textColor()} />
  <circle cx="134" cy="44" r={dodSize} class={textColor()} />
  <circle cx="4" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="24" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="14" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="4" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="4" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="14" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="24" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="34" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="44" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="54" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="64" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="74" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="84" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="94" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="104" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="114" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="324" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="444" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="124" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="224" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="334" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="454" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="134" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="234" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="344" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="464" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="144" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="244" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="354" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="474" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="254" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="364" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="484" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="154" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="264" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="374" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="164" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="274" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="384" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="494" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="174" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="284" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="394" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="504" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="184" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="404" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="514" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="194" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="414" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="294" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="524" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="204" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="304" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="424" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="534" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="214" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="314" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="154" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="184" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="544" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="554" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="564" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="434" cy="174" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="34" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="44" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="54" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="64" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="74" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="84" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="94" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="104" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="114" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="124" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="134" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="144" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="164" r={dodSize} class={backGroundColor()} />
  <circle cx="574" cy="174" r={dodSize} class={backGroundColor()} />
</svg>
